### ISSUE TITLE
There are many abbreviations of proper nouns in your parameter folder. Can you upload the complete name or explain some column names in vpatient_params.csv 

### ISSUE THREAD

**Issue by OneBirding** [jxx123/simglucose#19]

**Comment by jxx123** [comment]
Sorry for the late reply. Here is the original paper describing the model and the parameters https://pubmed.ncbi.nlm.nih.gov/17926672/, but I actually found the appendix of this paper is much more clear since it assembles all the equations and parameters together https://pubmed.ncbi.nlm.nih.gov/17926672/. 

@sumanabasu has volunteered to enhance the documentation. Hopefully, we will have a better documentation soon. Thanks!

**Comment by jxx123** [comment]
Sorry, just put a wrong link, here is the link for the 2nd paper https://pubmed.ncbi.nlm.nih.gov/20046650/ that includes a nice appendix of all the equations and parameters.

**Comment by aacelik** [comment]
Hi Jinyu, thanks for the simulator, it looks great. I have one question though. I want to understand how Gtb values are computed in vpatient_params.csv. In 2014 UVa/Padova paper equation (1), it says Gtb=Gpb*k1/k2; however, the Gtb values in vpatient_params.csv do not satisfy this equality. Also, S2009 paper do not state how Gtb is computed. Can you please explain how did you compute Gtb?
