### ISSUE TITLE
Input meal size different from recorded meal size

### ISSUE THREAD

**Issue by AdeLouis** [jxx123/simglucose#35]
Hi! Thanks for this package, super helpful. I was wondering why the inputted meal size and the actual recorded value in the output files differ. For example in the advanced usage example, the input size of the first meal is 45, but in the out put file, it registers as 15. 

From the code, it seems there is a division between meal size and sample time (= 3). 

Could you give more details on this? Thanks!

**Comment by jxx123** [comment]
Yeah, the recorded meal is a rate (g/min), so it is recorded as 15 g/min, and the sample time is 3 min, so the meal amount is 15 g/min * 3 min = 45 g. That is the area is the meal amount, not the value. 

Sorry if it is a bit confusing.

**Comment by AdeLouis** [comment]
Oh, I see that makes sense. This would also imply that in the basal-bolus controller, the bolus is being computed using the first 1/3 of the meal size and not the entire meal amount correct? So if a meal is 45g in total, the bolus amount is calculated using 15g (since its a third of the meal)

**Comment by jxx123** [comment]
Yes you can understand it that way. 

To be more specific, the meal info that the basal bolus controller gets is the full size (45g), I should've kept it more consistent. https://github.com/jxx123/simglucose/blob/8f6696a628543a553fd9d5aa55d935be23bd7b38/simglucose/controller/basal_bolus_ctrller.py#L30

Then the bolus is divided by the sample time here https://github.com/jxx123/simglucose/blob/8f6696a628543a553fd9d5aa55d935be23bd7b38/simglucose/controller/basal_bolus_ctrller.py#L82

So in the end you can say the bolus is based on 15g, because it is also a rate instead of the absolute amount.

**Comment by AdeLouis** [comment]
That makes sense. Thank you! I will close this issue then.

**Comment by lorenzobrigato** [comment]
I was checking this thread because I am not totally sure that the basal bolus controller gets is the full size of the meal as @jxx123 wrote in his last comment.

The meal that the Basal Bolus controller takes from the `kwargs` in the `def policy(self, observation, reward, done, **kwargs)`
https://github.com/jxx123/simglucose/blob/8f6696a628543a553fd9d5aa55d935be23bd7b38/simglucose/controller/basal_bolus_ctrller.py#L30
seems to already be in units of (g/min) and not (g). 

You can check that the `Step` namedtuple outputted by the `def step(self, action, reward_fun=risk_diff)` of the `T1DSimEnv` class returns the `meal` argument as the `CHO` variable.

The `CHO` variable is computed as a running average in the for loop
https://github.com/jxx123/simglucose/blob/8f6696a628543a553fd9d5aa55d935be23bd7b38/simglucose/simulation/env.py#L78

However, I printed these values, and two out of three times the `tmp_CHO` variable is always 0. An example print:
_
tmp_CHO  = 64
tmp_CHO = 0
tmp_CHO = 0
CHO  = 21.333333333333332
_

The CHO variable is then added to the CHO_hist variable
https://github.com/jxx123/simglucose/blob/8f6696a628543a553fd9d5aa55d935be23bd7b38/simglucose/simulation/env.py#L88
and, as I was previously mentioning, apparently returned in units of (g/min) and not (g)
https://github.com/jxx123/simglucose/blob/8f6696a628543a553fd9d5aa55d935be23bd7b38/simglucose/simulation/env.py#L112

Do you also see this issue happening @jxx123 ?
I think that an easy fix would be to multiply back the `CHO`  variable by `self.sample_time` if the goal is to have the `kwargs.get('meal')` in units of (g).
Clearly, let me know if I misanderstood something.
